baseurl = "https://philintheblank.me/" 
languageCode = "en-us"
title = "internet bloggo"
theme = "internet-weblog"
pygmentsstyle = "emacs"
Paginate = 10
googleAnalytics = "UA-140178220-1"

[author]
	Handle = "Nguyenhphil"
	SectionPagesMenu = "main"
	FirstName = "Phil"
	LastName = "Nguyen"
	AboutPage = "/about"
	Location = "Burlington, VT"
	FlickrID = "156401995@N06"

[params]
	Description = "A place to write and explore my curiosities."
	ShowCopyright = true
	RSSEnabled = false
	RSSMicropostTitles = false
	mainSections = [ "posts", "microposts", "projects", "photos" ]
	favicon = "sam.ico"
  homepage = "main"
  images = ["tn.png"]
  title = "Phil in the Blank"
  YearlyMicroposts = false
  
[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[[menu.main]]
	name = "Posts"
	weight = 1
	identifier = "posts"
	url = "/posts/"
	
	[[menu.main]]
   name = "Microposts"
   weight = 2
   identifier = "microposts"
   url = "/microposts/"

[[menu.main]]
   name = "Projects"
   weight = 3
   identifier = "projects"
   url = "/projects"
   